---
- name: ensure ca_path exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ ca_path }}/{{ ca_private_path }}"
    - "{{ ca_path }}/{{ ca_certs_path }}"
    - "{{ ca_path }}/{{ ca_requests_path }}"
    - "{{ ca_path }}/{{ ca_newcerts_path }}"
    - "{{ ca_path }}/{{ ca_extfiles_path }}"
    - "{{ ca_path }}/{{ ca_subject_keys_path }}"

- name: ensure index file exists
  file:
    path: "{{ ca_path }}/index.txt"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: check whether crlnumber file exists
  stat:
    path: "{{ ca_path }}/crlnumber"
  register: check_crlnumber

- name: init crlnumber file
  copy:
    dest: "{{ ca_path }}/crlnumber"
    content: "1000"
  when: not check_crlnumber.stat.exists

- name: ensure openssl config file exists
  template:
    src: "{{ ca_openssl_config_file }}.j2"
    dest: "{{ ca_path }}/{{ ca_openssl_config_file }}"

- name: generate ca key
  openssl_privatekey:
    path: "{{ ca_path }}/{{ ca_privatekey_path }}"
    passphrase: "{{ ca_passphrase }}"
    cipher: aes256

- name: init crl file
  command:
    chdir: "{{ ca_path }}"
    cmd: "openssl ca {{ ca_crl_params }}"
    creates: "{{ ca_crl_path }}"
