---
# tasks file for ca
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

# init
- name: set path for root CA
  set_fact:
    ca_path: "{{ ca_openssl_path }}/{{ ca_common_name }}/rootCA"
    ca_filename: rootCA
  when:
    - ca_init
    - ca_own_root

- name: init root CA
  include_tasks: init_ca.yml
  when:
    - ca_init
    - ca_own_root

- name: set path for CA
  set_fact:
    ca_path: "{{ ca_openssl_path }}/{{ ca_common_name }}"
    ca_filename: ca

- name: init CA
  include_tasks: init_ca.yml
  when: ca_init

- name: generate ca certificates
  include_tasks: generate_ca_certs.yml
  when:
    - ca_init
    - ca_own_root

- name: ensure publication location exists
  file:
    path: "{{ ca_publication_location }}"
    state: directory
    mode: "755"
    owner: root
    group: root
  when:
    - ca_publication_location is defined

- name: handle requests
  include_tasks: requests.yml
  loop: "{{ ca_requests }}"
  loop_control:
    loop_var: request
    label: "{{ request.name | default(request) }}"
  when:
    - ca_requests is defined
